baseurl = "https://bojanz.github.io/"
languageCode = "en-us"
title = "bojanz.github.io"
disqusShortname = "bojanz"
theme = "hugo-hikari-theme"

[permalinks]
	post = "/:slug"

[params]
	name = "Bojan Živanović (bojanz)"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

	pageNotFoundTitle = "Page not found"
	pageNotFoundSubtitle = "Sorry, but the requested page wasn’t <br> found on the server."

[params.offcanvas]
	# Menu items
	title = "Bojan Živanović"
	bio = "Open Sourcerer. Director of Engineering @[Platform.sh](https://platform.sh)"
	subscribe = "Subscribe"
	followme = "Follow me on"

	# Enable Google search
	search_enabled = false
	search = "Search"

	[[params.offcanvas.socialnetworks]]
		name = "GitHub"
		url = "https://github.com/bojanz"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "https://twitter.com/bojan_zivanovic"

[services]
	[services.googleAnalytics]
		ID = "G-47S0XERS5G"

[markup]
  [markup.highlight]
    noClasses = false
	codeFences = false
